clin_all = data.frame(NULL)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_1"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene2","Gene2","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_2"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene2","Gene2","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_3"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_4"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_5"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_6"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_7"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_8"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_9"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9,8),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_10"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene5","Gene5","Gene6","Gene6","Gene3-Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22,NA)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C","fusion")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant","fusion")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","A","F","B","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib","NA")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_11"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene6","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","E","F","E")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_12"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene6","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","D","F","D")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_13"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene6","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","B")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_14"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene6","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_15"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene5","Gene5")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_16"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene5","Gene5")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_17"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene1","Gene5","Gene5")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_18"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene3","Gene3")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_19"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene3","Gene3")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_20"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene3","Gene3")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_21"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene3","Gene3")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_22"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene4","Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_23"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene3","Gene3")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_24"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene4","Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_25"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene4","Gene4")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_26"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene2","Gene2","Gene5","Gene5")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","B","F","B")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_27"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene3","Gene3","Gene5","Gene5")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_28"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene3","Gene3","Gene5","Gene5")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_29"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene3","Gene3","Gene5","Gene5")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,11,22,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C","A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","C","F","C")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,"olarapib",NA,"alpelisib")
clin$C.CAT調査結果.変異情報TMB.TMB="16.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_30"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene3","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,NA)
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_31"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene1","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,NA)
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_32"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene4","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,NA)
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_33"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene3","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,NA)
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin=clin_tmp[c(1,8,9),]
clin$C.CAT調査結果.基本項目.ハッシュID="ID_34"
clin$C.CAT調査結果.変異情報.マーカー=c("TMB","Gene4","Gene6")
clin$C.CAT調査結果.変異情報.物理位置=c(NA,11,22)
clin$C.CAT調査結果.変異情報.変異内容=c(NA,"A111C","A111C")
clin$C.CAT調査結果.変異情報.変異種類=c("other_biomarker","small_scale_variant","small_scale_variant")
clin$C.CAT調査結果.エビデンス.エビデンスレベル=c(NA,"F","F")
clin$C.CAT調査結果.エビデンス.薬剤=c(NA,NA,NA)
clin$C.CAT調査結果.変異情報TMB.TMB="6.3Muts/Mb"
clin_all = rbind(clin_all,clin)
clin_all$C.CAT調査結果.変異情報.遺伝子=""
clin_all$C.CAT調査結果.基本項目.年齢.年.=43
clin_all$C.CAT調査結果.基本項目.検体採取日="2000-01-01"
write_excel_csv(clin_all, "tmpr.csv")